name: Go Unit Tests

on:
  push:
    branches:
      - '**'  # 任意のブランチ
    paths:
      - 'ut/fizzbuzz.go'
      - 'ut/fizzbuzz_test.go'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: チェックアウトリポジトリ
        uses: actions/checkout@v3

      - name: Go 環境のセットアップ
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'  

      - name: ユニットテストの実行
        working-directory: ut
        run: go test -v
